kubelet:
  labels:
    io.rancher.container.dns: true
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
    io.rancher.scheduler.global: true
  command:
  - kubelet
  - --api_servers=http://master:8080
  - --allow-privileged=true
  - --containerized=true
  - --register-node=true
  - --cloud-provider=rancher
  image: k8s:craig-dev
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  net: host
  pid: host
  ipc: host
  privileged: true
  links:
  - api-server:master

proxy:
  labels:
    io.rancher.container.dns: true
    io.rancher.scheduler.global: true
  command:
  - kube-proxy
  - --master=http://master:8080
  - --v=2
  image: k8s:craig-dev
  privileged: true
  net: host
  links:
  - api-server:master

etcd:
  command:
  - /usr/local/bin/etcd
  - --addr=127.0.0.1:4001
  - --bind-addr=0.0.0.0:4001
  - --data-dir=/var/etcd/data
  image: gcr.io/google_containers/etcd:2.0.12
  net: container:api-server

api-server:
  labels:
    io.rancher.sidekicks: etcd,scheduler,controller-manager,rancher-agent
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
  command: 
  - /usr/local/bin/kube-apiserver
  - --service-cluster-ip-range=10.42.0.0/16
  - --etcd-servers=http://localhost:4001
  - --insecure-bind-address=0.0.0.0
  - --insecure-port=8080
  - --cloud-provider=rancher
  image: gcr.io/google_containers/kube-apiserver:craig-dev
  ports:
  - "8080:8080"

scheduler:
  command:
  - /usr/local/bin/kube-scheduler
  - --master=127.0.0.1:8080
  image: gcr.io/google_containers/kube-scheduler:craig-dev
  net: container:api-server

controller-manager:
  command:
  - /usr/local/bin/kube-controller-manager
  - --master=127.0.0.1:8080
  - --cloud-provider=rancher
  image: gcr.io/google_containers/kube-controller-manager:craig-dev
  net: container:api-server
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment

rancher-agent:
  net: container:api-server
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent_service.labels_provider: true
  image: rancher/kubernetes-agent:dev
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
