api-server:
  service_schemas:
    kubernetesReplicationController:
      resource_fields:
        template:
          type: json
          create: true
          read: true
          update: true
    kubernetesService:
      resource_fields:
        template:
          type: json
          create: true
          read: true
          update: true
